set-option -sg escape-time 10

set-option -g default-terminal "screen-256color"

# Split horizontally (top/bottom) in current path
bind '"' split-window -v -c "#{pane_current_path}"

# Split vertically (left/right) in current path
bind % split-window -h -c "#{pane_current_path}"

# Open new window in current path
bind c new-window -c "#{pane_current_path}"
